dist: focal
language: bash
branches:
  only:
  - main
env:
  matrix:
  - tf_version=1.0.5 tf_init_cli_options="-input=false" tf_validation_cli_options=""
    tf_plan_cli_options="-lock=false -input=false" tf_apply_cli_options="-auto-approve
    -input=false"
  global:
  - secure: Z91syHnI4FAvs1/kTmVmFfiHTuJTR9Nkc1j5Tv0+nRzape6NTDcuXTuO3mE3WiLOfTdUw2pJn47Ev3cKtRAN1zl4e8860eg+iJ+Agq3CyfVjKBRSSuYDd4KSSdFs0TY1wvVfUsXlVlHzfEqI/WJzE8TLMlof2jwWlVXzZmlpD460xwNujl7wj7Zeay/DnfYYwp1Zv+vop3cW3EpJzDWMWCC1g2QjLJRYToxF0vFLrhgspEUZVL5nH0x272ExGfsC9mzqtU4q8GJNbOd/5P2MOxXdQYiWMbjJe7tSSnOfeHDahmNIl0zXg7yGcU6jbeQMKCaE+0ripe8m9GHfuhBxyG/EflqeytlHvZAqLuXwL5yAiUZlHrMtw4KRoGddQipPyujjf3cmdvFaA/oY9KWabVgIlRdJR7VFBJltu4ivvsszFLJCiP28vfCwGLEyoZOiRFN4/HWpKFW2P9IfR0jpfheJf2auLR03LXPwMEKA/xnDW6Cs56v7jJZpaFt3bseoYPxT1tX/i4jpYixhE3ASAXy1oH0EwArHkV6L7eUQRJOyM2w/vYvzlPqkwBMnarIUFcgSRSytx+HnXanRZO0iMewdi2lQtGoo9PcQMcSB0OckaZ1T8rvIWGVgwM5bvClTDIKuk+lZVweX5kTQ85qfW9CzSRgPDkgsa35stRYh84E=
  - secure: CUCbAk4d+epCKAJNcl8VQSvYjbtb4KaSMVhzyeBJdipLOIokC3tytxmuQTUAXhawT3mGbqlZ0gFO3LMa8IDN4qt6OApLfE3Z+lICSxoNw/CfpGYb/wzUhWJ7Un+ZCWYMHJlPH3vDC1Xtk+COKistYP/JLvqcr7+fv7+nrI7x52tZWznVw9lXEP+0EpoaxugOrfBRHz40PSSPk2Xgb7K49ucpK9VlBtriUgUW07i2WvmYeciM87IGX8w4VuKAQC8+iSbO0bW7ebkpreZqMeGQdP3oKdU8B6gVE5WvMKyZz0wEOhqePOoZSpTTND8fkGk/EoSj4CuZ2KzMB/MuxgZ823JetwaZ4nbYayZZ0DPTp0ZB1wW0DewUYxVYAWiYICmkD+zbmj+rDh8gk8O0shWkpkgFZ7d8cFBMCbdyR0fYRHcXnpcwjUhGuiYtx849jXgfTt5gFMZlIL7+hpJlaGzRddkiJZyKRKmucsfdG2XeroM1kVRguNym7iwNNbgcFcStlKitidwI55w+plCvC8Bmjw/dOr05+iPxCaY8uYnWiLCOFDZIIIDLpEkk7OjwQec/HtmdiXJH3BT+D9TzsLq1xO+AdnUHJuLMa2DjEeLTT3bSJf5wRYiE3GNdcBPhXLQbiDu95CaBV5Oc8Dyvfq/vQPq8ZKxU61MbEDhdFamKvdI=
before_install:
- cd ./scripts
- export KUBERNETES_SERVICE_HOST=""
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
jobs:
  include:
  - stage: terraform plan
    if: type IN (pull_request)
    script:
    - echo "Executing Terraform Plan on pull request code"
    - terraform init $tf_init_cli_options
    - terraform validate $tf_validation_cli_options
    - terraform plan $tf_plan_cli_options
  - stage: terraform apply
    if: type IN (push)
    script:
    - echo "Executing Terraform Apply on merged code"
    - terraform init $tf_init_cli_options
    - terraform apply $tf_apply_cli_options -var="AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
      -var="AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" --var="app_version=1.0.0"
