dist: focal
language: bash
branches:
  only:
  - main
env:
  matrix:
  - tf_version=1.0.5 tf_init_cli_options="-input=false" tf_validation_cli_options=""
    tf_plan_cli_options="-lock=false -input=false" tf_apply_cli_options="-auto-approve
    -input=false"
  global:
  - secure: AxccoJiob7W/WbIO28GlXyUsXTyKW8RZpW5ijHN0orpmVGkA+DEASYgVVPGLRLHa/sdy7KmxXQ6fT44Wm6cuqUxd338n8uTCwG23fTfLd9159wauDSMs94MOLJor34793cfLBMjCX5kkG91JSwlB3WbumLgyeN0yLlOicEwREiYUPzLJVGhNmA8GSmezTPMdrfZVJqAEPj+rLdNPSnONbEORZM2RvOEVYZBqm6bTJBhh8aVtezkY/NTeOc325I14nTdtn6HsZRHiCqffjousHYdYG+atLuDunUDVRDO1TUCMyvR8V/63XqaPH7JeoaCb+jEpMA8+nyGleUTVcCFtZGgDcTs1FA9l9k3gNN2VO2sBpa4y9qXZaQcO/e/Nzy/hX3V+7UIytUIDxxkW16busHJUejeOc8/ky+hzuxHQJITtdOX6GiHvqJn2h2jONJLzSa2nt4/bCpc/K3WAPzSStb37VBl/VHu01x/xT2m7Iw5aUarWCREAuvRMloUPkKhJpxBPalUwpE0wLgPWbaomRhGKyuKqQzVVNcUrpcF2FSKlGlk41lLKqVNvG4/gvjFAfax+7oNeTHv3RUoXnmjpyl7L/qjBc3LgpykBQTXGhjiW87ief8YPnawkve7mLQbSFtQoyU+8tvdcabDI/i69pibePIqiumPGi77P5N2F0Q0=
  - secure: FHwnLRN/TQZRq5aAstyz3OoqrztCBtbKhjHdm4XsXRH3p2Q2Cc93zvdOqnG1j0tWjGBBoqXcVFUyeXP+NhyDoCGAbVr14PGstSuABft1qT4XgNixIWKnS2nUPx90fWM4Wfb0cpMkQAAdmFH8mRSbVxMvFHhuWELBau6YIYh4ds2jb+QeE+6fVpv2euWji3hoBAgZC4mcusNZL1EH+BeRK1G6z4AW8NdRlBSKOAu3hoYtntBlql2PcrLQrDVrPlDG4qDJx3+TjLQo7eZ1RSav6l4UepikCNIPhblL3B2LquUpb0ehr+fEbbNUqh0ZYCCbLKCr1rhs8ccnbIMaAhAS3ERpWTNNdwLRCL4w441oRdqwP3iLUeNb8uxMmxJQTpvEPlDq/2KKjArGsa32YzpnyL7vfkM/lCCKcfFJzHBbMtanrtF2XZuZsGJnoD5GCyDBDoumaCMpk7tJ2rxZxny0qN/gQMg2AAIT6HBmPVmGksZ6pbiNoxIkekU1hoSJlzEOv6DHcdoptezzm8xC57Qc1u2rFjkSrHilO6eJZ0rGYb1dyFAYDP/EXrGxUKQCHtpBkFbiAu2FhVX/OXseJZ3PyLsrWQsFTtSnUuZlFPnlLSTvns9vakdLuspLZStVr3oBRh99MZcFWDstiKKFjaRDbYTZDLmg/i142YQq6VBzKDI=
before_install:
- cd ./scripts
- export KUBERNETES_SERVICE_HOST=""
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
jobs:
  include:
  - stage: terraform plan
    if: type IN (pull_request)
    script:
    - echo "Executing Terraform Plan on pull request code"
    - terraform init $tf_init_cli_options
    - terraform validate $tf_validation_cli_options
    - terraform plan $tf_plan_cli_options
  - stage: terraform apply
    if: type IN (push)
    script:
    - echo "Executing Terraform Apply on merged code"
    - terraform init $tf_init_cli_options
    - terraform apply $tf_apply_cli_options -var="AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
      -var="AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" --var="app_version=1.0.0"
